### PR TITLE
pagination bug fix

### PR DESCRIPTION
**Pull request by kmakai**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kmakai Hey! I couldn't find an option to create a quiz, as this is one of the requirements. Am I missing something? 😟🔎🔎🔎

**Comment by kmakai** [comment]
Oh wow, I misunderstood the requirements I'm gonna have to redo a bit of it.

**Comment by TheCSharpAcademy** [comment]
@kmakai Let me know if you need any help 😁

**Comment by TheCSharpAcademy** [comment]
@kmakai closing the PR for admin purposes but feel free to reopen when you're ready 😊

**Pull request closed without merging**
